### ISSUE TITLE
Image shape requirement

### ISSUE THREAD

**Issue by YangLuYang** [hszhao/semseg#13]
My customized dataset` image.shape=(3, 512, 512)`.
In `psanet.py`  line 157 
```
assert(x_size[2]-1)%8 == 0 and (s_size[3]-1)%8==0
h =  int((x_size[2] - 1)  / 8 * self.zoom_factor + 1)
w = int((x_size[3] - 1) /8 * self.zoom_factor + 1)
````
How should I modification the code to work ?
Ps:
if I just comment line 157,  it will throw a `RuntimeError` in `pasnet.py` line 98
```
invalid argument 0: Sizes of tensors must match except in dimension1, Got 63 and 64 in dimension 2
```

**Comment by hszhao** [comment]
The required input size should be 8n+1. If you are using the size of 8n, you need to change this checking part and the upsampling/interpolation part.
