### ISSUE TITLE
OMP: Error #13: Assertion failure at z_Linux_util.cpp(2361).

### ISSUE THREAD

**Issue by zhixuanli** [hszhao/semseg#16]
When trying to use multithread, the following error occurs:

```
OMP: Hint Please submit a bug report with this message, compile and run commands used, and machine configuration info including native compiler and ope│··································
rating system versions. Faster response will be obtained by including all program sources. For information on submitting this issue, please see http://│··································
www.intel.com/software/products/support/.                                                                                                              │··································
OMP: Error #13: Assertion failure at z_Linux_util.cpp(2361).                                                                                           │··································
OMP: Hint Please submit a bug report with this message, compile and run commands used, and machine configuration info including native compiler and ope│··································
rating system versions. Faster response will be obtained by including all program sources. For information on submitting this issue, please see http://│··································
www.intel.com/software/products/support/.                                                                                                              │··································
OMP: Error #13: Assertion failure at z_Linux_util.cpp(2361).                                                                                           │··································
OMP: Hint Please submit a bug report with this message, compile and run commands used, and machine configuration info including native compiler and ope│··································
rating system versions. Faster response will be obtained by including all program sources. For information on submitting this issue, please see http://│··································
www.intel.com/software/products/support/.                                                                                                              │··································
OMP: Error #13: Assertion failure at z_Linux_util.cpp(2361).                                                                                           │··································
OMP: Hint Please submit a bug report with this message, compile and run commands used, and machine configuration info including native compiler and ope│··································
rating system versions. Faster response will be obtained by including all program sources. For information on submitting this issue, please see http://│··································
www.intel.com/software/products/support/.                                                                                                              │··································
OMP: Error #13: Assertion failure at z_Linux_util.cpp(2361).                                                                                           │··································
OMP: Hint Please submit a bug report with this message, compile and run commands used, and machine configuration info including native compiler and ope│··································
rating system versions. Faster response will be obtained by including all program sources. For information on submitting this issue, please see http://│··································
www.intel.com/software/products/support/.                                                                                                              │··································
OMP: Error #13: Assertion failure at z_Linux_util.cpp(2361).                                                                                           │··································
OMP: Hint Please submit a bug report with this message, compile and run commands used, and machine configuration info including native compiler and ope│··································
rating system versions. Faster response will be obtained by including all program sources. For information on submitting this issue, please see http://│··································
www.intel.com/software/products/support/.                                                                                                              │··································
OMP: Error #13: Assertion failure at z_Linux_util.cpp(2361).                                                                                           │··································
OMP: Hint Please submit a bug report with this message, compile and run commands used, and machine configuration info including native compiler and ope│··································
rating system versions. Faster response will be obtained by including all program sources. For information on submitting this issue, please see http://│··································
www.intel.com/software/products/support/.                                                                                                              │··································
OMP: Error #13: Assertion failure at z_Linux_util.cpp(2361).                                                                                           │··································
OMP: Hint Please submit a bug report with this message, compile and run commands used, and machine configuration info including native compiler and ope│··································
rating system versions. Faster response will be obtained by including all program sources. For information on submitting this issue, please see http://│··································
www.intel.com/software/products/support/.                                                                                                              │··································
Traceback (most recent call last):                                                                                                                     │··································
  File "tool/train.py", line 456, in <module>                                                                                                          │··································
    main()                                                                                                                                             │··································
  File "tool/train.py", line 106, in main                                                                                                              │··································
    mp.spawn(main_worker, nprocs=args.ngpus_per_node, args=(args.ngpus_per_node, args))                                                                │··································
  File "/home/lzx/.conda/envs/pytorchseg10/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn                             │··································
    while not spawn_context.join():                                                                                                                    │··································
  File "/home/lzx/.conda/envs/pytorchseg10/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 107, in join                              │··································
    (error_index, name)                                                                                                                                │··································
Exception: process 2 terminated with signal SIGABRT
```

This will happen when multiprocessing_distributed and use_apex are True.
Configuration details:
```
TRAIN:
  arch: psp
  layers: 101
  sync_bn: False  # adopt syncbn or not
  train_h: 585
  train_w: 585
  scale_min: 0.5  # minimum random scale
  scale_max: 2.0  # maximum random scale
  rotate_min: -10  # minimum random rotate
  rotate_max: 10  # maximum random rotate
  zoom_factor: 8  # zoom factor for final prediction during training, be in [1, 2, 4, 8]
  ignore_label: 255
  aux_weight: 0.4
  train_gpu: [0, 1, 2, 3, 4, 5, 6, 7]
  workers: 16  # data loader workers
  batch_size: 16  # batch size for training
  batch_size_val: 8  # batch size for validation during training, memory and speed tradeoff
  base_lr: 0.01
  epochs: 200
  start_epoch: 0
  new_epoch: 300  # for resume, how many new epochs to train
  power: 0.9
  momentum: 0.9
  weight_decay: 0.0001
  manual_seed: 520
  print_freq: 10
  save_freq: 1
  save_path: exp/cityscapes/pspnet101/model
  weight:  # path to initial weight (default: none)
  resume:  # path to latest checkpoint (default: none)
  evaluate: True # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
Distributed:
  dist_url: tcp://127.0.0.1:6789
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0
  use_apex: True
  opt_level: 'O0'
  keep_batchnorm_fp32:
  loss_scale:
```

I have tried to do some search but they are not working. 

Could you please give me some advice?

Thanks a lot!

**Comment by hszhao** [comment]
> When trying to use multithread, the following error occurs:
> 
> ```
> OMP: Hint Please submit a bug report with this message, compile and run commands used, and machine configuration info including native compiler and ope│··································
> rating system versions. Faster response will be obtained by including all program sources. For information on submitting this issue, please see http://│··································
> www.intel.com/software/products/support/.                                                                                                              │··································
> OMP: Error #13: Assertion failure at z_Linux_util.cpp(2361).                                                                                           │··································
> OMP: Hint Please submit a bug report with this message, compile and run commands used, and machine configuration info including native compiler and ope│··································
> rating system versions. Faster response will be obtained by including all program sources. For information on submitting this issue, please see http://│··································
> www.intel.com/software/products/support/.                                                                                                              │··································
> OMP: Error #13: Assertion failure at z_Linux_util.cpp(2361).                                                                                           │··································
> OMP: Hint Please submit a bug report with this message, compile and run commands used, and machine configuration info including native compiler and ope│··································
> rating system versions. Faster response will be obtained by including all program sources. For information on submitting this issue, please see http://│··································
> www.intel.com/software/products/support/.                                                                                                              │··································
> OMP: Error #13: Assertion failure at z_Linux_util.cpp(2361).                                                                                           │··································
> OMP: Hint Please submit a bug report with this message, compile and run commands used, and machine configuration info including native compiler and ope│··································
> rating system versions. Faster response will be obtained by including all program sources. For information on submitting this issue, please see http://│··································
> www.intel.com/software/products/support/.                                                                                                              │··································
> OMP: Error #13: Assertion failure at z_Linux_util.cpp(2361).                                                                                           │··································
> OMP: Hint Please submit a bug report with this message, compile and run commands used, and machine configuration info including native compiler and ope│··································
> rating system versions. Faster response will be obtained by including all program sources. For information on submitting this issue, please see http://│··································
> www.intel.com/software/products/support/.                                                                                                              │··································
> OMP: Error #13: Assertion failure at z_Linux_util.cpp(2361).                                                                                           │··································
> OMP: Hint Please submit a bug report with this message, compile and run commands used, and machine configuration info including native compiler and ope│··································
> rating system versions. Faster response will be obtained by including all program sources. For information on submitting this issue, please see http://│··································
> www.intel.com/software/products/support/.                                                                                                              │··································
> OMP: Error #13: Assertion failure at z_Linux_util.cpp(2361).                                                                                           │··································
> OMP: Hint Please submit a bug report with this message, compile and run commands used, and machine configuration info including native compiler and ope│··································
> rating system versions. Faster response will be obtained by including all program sources. For information on submitting this issue, please see http://│··································
> www.intel.com/software/products/support/.                                                                                                              │··································
> OMP: Error #13: Assertion failure at z_Linux_util.cpp(2361).                                                                                           │··································
> OMP: Hint Please submit a bug report with this message, compile and run commands used, and machine configuration info including native compiler and ope│··································
> rating system versions. Faster response will be obtained by including all program sources. For information on submitting this issue, please see http://│··································
> www.intel.com/software/products/support/.                                                                                                              │··································
> Traceback (most recent call last):                                                                                                                     │··································
>   File "tool/train.py", line 456, in <module>                                                                                                          │··································
>     main()                                                                                                                                             │··································
>   File "tool/train.py", line 106, in main                                                                                                              │··································
>     mp.spawn(main_worker, nprocs=args.ngpus_per_node, args=(args.ngpus_per_node, args))                                                                │··································
>   File "/home/lzx/.conda/envs/pytorchseg10/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn                             │··································
>     while not spawn_context.join():                                                                                                                    │··································
>   File "/home/lzx/.conda/envs/pytorchseg10/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 107, in join                              │··································
>     (error_index, name)                                                                                                                                │··································
> Exception: process 2 terminated with signal SIGABRT
> ```
> 
> This will happen when multiprocessing_distributed and use_apex are True.
> Configuration details:
> 
> ```
> TRAIN:
>   arch: psp
>   layers: 101
>   sync_bn: False  # adopt syncbn or not
>   train_h: 585
>   train_w: 585
>   scale_min: 0.5  # minimum random scale
>   scale_max: 2.0  # maximum random scale
>   rotate_min: -10  # minimum random rotate
>   rotate_max: 10  # maximum random rotate
>   zoom_factor: 8  # zoom factor for final prediction during training, be in [1, 2, 4, 8]
>   ignore_label: 255
>   aux_weight: 0.4
>   train_gpu: [0, 1, 2, 3, 4, 5, 6, 7]
>   workers: 16  # data loader workers
>   batch_size: 16  # batch size for training
>   batch_size_val: 8  # batch size for validation during training, memory and speed tradeoff
>   base_lr: 0.01
>   epochs: 200
>   start_epoch: 0
>   new_epoch: 300  # for resume, how many new epochs to train
>   power: 0.9
>   momentum: 0.9
>   weight_decay: 0.0001
>   manual_seed: 520
>   print_freq: 10
>   save_freq: 1
>   save_path: exp/cityscapes/pspnet101/model
>   weight:  # path to initial weight (default: none)
>   resume:  # path to latest checkpoint (default: none)
>   evaluate: True # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
> Distributed:
>   dist_url: tcp://127.0.0.1:6789
>   dist_backend: 'nccl'
>   multiprocessing_distributed: True
>   world_size: 1
>   rank: 0
>   use_apex: True
>   opt_level: 'O0'
>   keep_batchnorm_fp32:
>   loss_scale:
> ```
> 
> I have tried to do some search but they are not working.
> 
> Could you please give me some advice?
> 
> Thanks a lot!

Hi, are you following the recommend installing steps of apex?
https://github.com/NVIDIA/apex

$ git clone https://github.com/NVIDIA/apex
$ cd apex
$ pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./

**Comment by zhixuanli** [comment]
```
git clone https://github.com/NVIDIA/apex.git && cd apex && pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" .
```

Thanks for your reply, I have installed following the same command as you.


And I have checked the following matters:
```
Please check torch._C._GLIBCXX_USE_CXX11_ABI is False at first.

$ python
>>> import torch
>>> torch._C._GLIBCXX_USE_CXX11_ABI
False
```

Still having this error.

I have run your code with multi-thread function open successfully on the other machine, and this machine newly bought.

Maybe my apex version is too new? 


Thanks for your reply!!

**Comment by zhixuanli** [comment]
This configuration has no bug (but slow):
```
Distributed:
  dist_url: tcp://127.0.0.1:6789
  dist_backend: 'nccl'
  multiprocessing_distributed: False
  world_size: 1
  rank: 0
  use_apex: True
  opt_level: 'O0'
  keep_batchnorm_fp32:
  loss_scale:
```

**Comment by zhixuanli** [comment]
I have searched for many documents but never seen this bug...

The most related one says that it's the problem of the intel cpu...

It's hard to believe that.

BTW, the configuration of this machine:

- CPU: Intel Xeon Silver 4110
- GPU: 8 x 2080TI

**Comment by zhixuanli** [comment]
Could you please tell me your apex version? THX
@hszhao

**Comment by zhixuanli** [comment]
It's not related with apex version.

The solution is add `export KMP_INIT_AT_FORK=FALSE` to train.sh.

Such as:
```
#!/bin/sh
PARTITION=gpu
PYTHON=python

dataset=$1
exp_name=$2
exp_dir=exp/${dataset}/${exp_name}
model_dir=${exp_dir}/model
result_dir=${exp_dir}/result
config=config/${dataset}/${dataset}_${exp_name}.yaml
now=$(date +"%Y%m%d_%H%M%S")

mkdir -p ${model_dir} ${result_dir}
cp tool/train.sh tool/train.py ${config} ${exp_dir}

export PYTHONPATH=./
export KMP_INIT_AT_FORK=FALSE
#sbatch -p $PARTITION --gres=gpu:8 -c16 --job-name=train \
$PYTHON -u tool/train.py \
  --config=${config} \
  2>&1 | tee ${model_dir}/train-$now.log

```

Reference: 
https://github.com/ContinuumIO/anaconda-issues/issues/11294

And the training speed is really very fast. The predicted training time is about 8 hours for psp101 on cityscapes dataset.

Thanks for your code again, it's really helpful!
