### ISSUE TITLE
Getting lower mIoU in the cityscape

### ISSUE THREAD

**Issue by Ximoi** [hszhao/semseg#17]
Hi, I used the checkpoint downloaded from the provided GoogleDrive---pspnet/train-epoch-200 to test the cityscape val dataset using 'sh tool/test.sh cityscapes pspnet50', 
but I got very low mIoU:  Eval result: mIoU/mAcc/allAcc 0.0038/0.0150/0.0069.
After I saw the colored predicted picture, I find the satisfactory results. It seems the gray predicted picture is painted with wrong ids !
can you tell me how to fix it ?

**Comment by Ximoi** [comment]
Sorry, I fix it. Thank you

**Comment by Jee-King** [comment]
Hi, I met the same problem, how to solve it?

**Comment by fido20160817** [comment]
@Ximoi how you fix it?

**Comment by Ximoi** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在学习中,很忙,以后再聊!~~~~
