### ISSUE TITLE
some problem with resize

### ISSUE THREAD

**Issue by ZhaoyangLi-nju** [hszhao/semseg#19]
when I used train images with resize(1024*2048),randomcrop size(512*1024),I can get the performance in valsets with 76.35,but when I changed resize(512*1024),randomcrop(384*768)，I only can get the performance in valsets with 72. can you help me?(bencause I have to use the setting for the future work),thank you very much

**Comment by zhixuanli** [comment]
The bigger the training image size, the better the performance.
