### ISSUE TITLE
Training is slow

### ISSUE THREAD

**Issue by LiangTinting** [hszhao/semseg#2]
Hi, Thank you for sharing the code! The work is very exciting and the code is elegantly written.
Here is a question. I trained on cityscapes resnet101 with the default setting except batch_size is set to 8. For 14 hours I only trained 96epochs. It trains quickly at the beginning and then gets slower and slower. 
Hardware information: 2 v100 GPUs(32G GPU memory).  The loss does not converge well.
![image](https://user-images.githubusercontent.com/18143311/58846156-c6d93300-86b0-11e9-9b9f-7b939e5af68d.png)

**Comment by hszhao** [comment]
Hi, the total training time might be different with different configurations. The listed time is tested with 8 GTX2080 TI GPUs and batch size 16.
