### ISSUE TITLE
Could semseg run on multi nodes?

### ISSUE THREAD

**Issue by zhixuanli** [hszhao/semseg#20]
@hszhao 
Is distributed training supported?

If the answer is yes, could you give me some instructions to run on multi nodes?

Thank you!

**Comment by hszhao** [comment]
Hi, I have not tested yet. You may have a try following the official instructions.
https://github.com/pytorch/examples/tree/master/imagenet

**Comment by zhixuanli** [comment]
Thank you!
I'll try it later!
