### ISSUE TITLE
About train on my own datasets.

### ISSUE THREAD

**Issue by chccgiven** [hszhao/semseg#23]
Hi~! I want to train PSPNet on my own datasets. My own datasets:  original images + gray label images(I have set the useful class as 0-(C-1) and the ignoring class as 255. The gray value of each pixel is the class number). 

Now I want to know how to set up the $DATASET$_colors.txt? Can I set up as follows? 
1
2
3
...
Hope for your reply, thanks!

**Comment by 864546664** [comment]
have you solved the problem?

**Comment by hszhao** [comment]
Hi, the colors do not matter, they are just for visualization. You can set as in https://github.com/hszhao/semseg/blob/master/dataset/voc2012/voc2012_colors.txt
