### ISSUE TITLE
uploaded pth model-weigths for PSPNet ResNet50/101 CityScapes?

### ISSUE THREAD

**Issue by tatigabru** [hszhao/semseg#25]
Any chance you could upload trained models weights on cityscapes dataset for PSPNet ResNet50/101 on google cloud?
I have no GPU and just want to do the inference on the new data

Thanks,
Tanya

**Comment by hszhao** [comment]
Hi, you can find the link in README.md.
https://drive.google.com/drive/folders/15wx9vOM0euyizq-M1uINgN0_wjVRf9J3

**Comment by xqsong-segnet** [comment]
We need trained models weights on the CityScapes dataset, not pre-trained models weights on the Imagenet dataset

**Comment by xqsong-segnet** [comment]
We need trained models weights on the CityScapes dataset, not pre-trained models weights on the Imagenet dataset,Thanks!
