### ISSUE TITLE
Resnet training procedure

### ISSUE THREAD

**Issue by pratyusha972** [hszhao/semseg#26]
@hszhao, Did you train ResNet models on Imagenet dataset with dilated convolutions or use the kernels of original resnet model in PSPNet as dilated kernels? 
I have used your pretrained resnet weights for initialising PSPNet and it's achieving published accuracy on validation dataset. I have trained Resnet model with changed architecture (3 kernels of (3,3) shape instead of 1 (7,7) kernel) without dilated convolutions and used it for training PSPNet, but there is a lot of deviation in accuracy. Could you please let me know the training protocol of Resnet models.

**Comment by hszhao** [comment]
Hi, I trained ResNet models with all dilation set to 1, so no dilated convolutions are used when training classification models. What is your classification model's accuracy? Have you loaded the right weights when training the segmentation model?
