### ISSUE TITLE
How to set up data and labels

### ISSUE THREAD

**Issue by shihaokun** [hszhao/semseg#4]
for example:
I have data and labels, Just identify the building from the picture.so labe just have backdrop and building,its 0 and 255.I revise the txt file in dataset.I put then in right position and created a right txt file, but the loss very big or little,
misconvergence .I dont know why?
because I just have the building data and labels?
And when I test, found a color file and a gray file, I have no idea what that means?

can you tell me how to do please?

**Comment by hszhao** [comment]
Hi, if there are only two categories: foreground buildings and background, you can set buildings as 0 and background as 1 (e.g., background in PASCAL VOC is a valid category).
