### ISSUE TITLE
some question about test.py ?

### ISSUE THREAD

**Issue by HiIcy** [hszhao/semseg#41]
I cant' understand the mean about follow code:
```
    def scale_process(self, image, crop_h, crop_w, h, w, mean, std=None, stride_rate=2 / 3):
        ori_h, ori_w, _ = image.shape
        # 填充周边
        pad_h = max(crop_h - ori_h, 0)
        pad_w = max(crop_w - ori_w, 0)
        pad_h_half = int(pad_h / 2)
        pad_w_half = int(pad_w / 2)
        if pad_h > 0 or pad_w > 0:
            image = cv2.copyMakeBorder(image, pad_h_half, pad_h - pad_h_half, pad_w_half, pad_w - pad_w_half,
                                       cv2.BORDER_CONSTANT, value=mean)
        new_h, new_w, _ = image.shape
        # FAQ:
        stride_h = int(np.ceil(crop_h * stride_rate))
        stride_w = int(np.ceil(crop_w * stride_rate))
        grid_h = int(np.ceil(float(new_h - crop_h) / stride_h) + 1)
        grid_w = int(np.ceil(float(new_w - crop_w) / stride_w) + 1)
        prediction_crop = np.zeros((new_h, new_w, self.numclass), dtype=float)
        count_crop = np.zeros((new_h, new_w), float)
        for index_h in range(0, grid_h):
            for index_w in range(0, grid_w):
                s_h = index_h * stride_h
                e_h = min(s_h + crop_h, new_h)
                s_h = e_h - crop_h
                s_w = index_w * stride_w
                e_w = min(s_w + crop_w, new_w)
                s_w = e_w - crop_w
                image_crop = image[s_h:e_h, s_w:e_w].copy()
                count_crop[s_h:e_h, s_w:e_w] += 1
                prediction_crop[s_h:e_h, s_w:e_w, :] += self.net_process(image_crop, mean, std)
        prediction_crop /= np.expand_dims(count_crop, 2)
        ..........
````
i know that it need to process with the train height、width,But I dont't understand! Appreciate with any suggest!

**Comment by Scarecrow0** [comment]
This part is for segmenting the image patch by patch.

**Comment by HiIcy** [comment]
oh,thank for your reply,i'm sorry that it's late to reply you

**Comment by baibaidj** [comment]
May I ask why you adopted the strategy as manifested by the scale_process for inference other than multi-scale inference? 
For me, the strategy is first to enlarge the original image (say 2048), then crop several patches of size 713*713 (identical to the size used during training) for inference, and finally put all the predicted mask of these patches together into one final mask and resize the final mask to the original size. 
So even for single scale inference, the model have made multiple predictions for a single image.  
Is it the case that you have done experiments showing that this inference strategy gave rise to better results? But how better? 
This trick was not mentioned in the paper.  It could be great to see a few comments on this. 

Thank you.

**Comment by sungxoo** [comment]
@baibaidj, @hszhao 
Hi, I agree with your opinion.
I don't know if the test input size can be set to 713x713.
The test size is same with the train size.
So, the performance of 713x713 is better than the original image size 1024x2048.
Shouldn't we have to test the original size to verify the model?
And can you say that the performance evaluated with several small patches (713x713) is the same as the performance reported in the paper?
I would be grateful for your answer. @hszhao

**Comment by AndreyStille** [comment]
@hszhao
Hello
Would you bother answering peoples questions above?
