### ISSUE TITLE
cityscapes_colors.txt and cityscapes_names.txt missed

### ISSUE THREAD

**Issue by shanjiuvspikaqiu** [hszhao/semseg#63]
Thank you for your codes. I did not find **cityscapes_colors.txt** and **cityscapes_names.txt** described in .yaml file in the google drive. 
What are their format?

THX and have a nice day!

**Comment by Co2Link** [comment]
They come with the repository, under the 'semseg/data/cityscapes'

**Comment by shanjiuvspikaqiu** [comment]
@ling9601 Thank you! I found it! :P Have a nice day!
