### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by hust-kevin** [hszhao/semseg#8]
when I run the train.sh

sometimes error is:
`RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED`

sometimes error is:
`RuntimeError: cuDNN error: CUDNN_STATUS_ALLOC_FAILED`

and maybe 
`RuntimeError: CUDA error: device-side assert triggered`

I use 
pytorch 1.1
cuda 9.0
cudnn 7.1.4

**Comment by YangLuYang** [comment]
> when I run the train.sh
> 
> sometimes error is:
> `RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED`
> 
> sometimes error is:
> `RuntimeError: cuDNN error: CUDNN_STATUS_ALLOC_FAILED`
> 
> and maybe
> `RuntimeError: CUDA error: device-side assert triggered`
> 
> I use
> pytorch 1.1
> cuda 9.0
> cudnn 7.1.4

你好，我现在也出现了第三个问题，你是怎么解决的？

**Comment by yuwen37** [comment]
hello，have you solved the problem for train error?
I have the same problem:
RuntimeError: CUDA error: device-side assert triggered.
How did you solve it？
