### ISSUE TITLE
lower metrics

### ISSUE THREAD

**Issue by fido20160817** [hszhao/semseg#90]
ade20k: Eval result: mIoU/mAcc/allAcc 0.0008/0.0021/0.0193. by running test.py

**Comment by fido20160817** [comment]
I finally got normal results at https://github.com/hszhao/semseg after testing multiple codes. The key is to transform the gt labels rightly (for training and evaluation).
for cityscapes: https://github.com/fyu/drn/tree/master/datasets/cityscapes. (you can transform gt labels ahead)
for ade20k: https://github.com/CSAILVision/semantic-segmentation-pytorch/blob/master/mit_semseg/dataset.py#L70   (you can transform gt inside the code, not ahead training or evaluaiton)
```python 
def segm_transform(self, segm):
        # to tensor, -1 to 149
        segm = torch.from_numpy(np.array(segm)).long() - 1
        return segm
```
I have to calculate mIoU/mAcc/allAcc for my task, but semantic segmentation not my research, so it really takes me some time to calculate these metrics. Hope this is helpful to others.

**Comment by BolinDeng98** [comment]
Hi, I am also facing this problem, can you explain it in more detail, thanks!

**Comment by BolinDeng98** [comment]
@fido20160817, can you explain it in more detail, I tried but failed.
